AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minecraft Server on AWS EC2'
Resources:
  MinecraftSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH and Minecraft server port'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0


  MinecraftServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m6i.xlarge
      ImageId: ami-079ea43d31a4fb4d8
      KeyName: MinecraftKey
      SecurityGroups:
        - Ref: MinecraftSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 16 # Size of the EBS volume in GB

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          /bin/bash -c "$(curl -sSL https://raw.githubusercontent.com/jstockdi/minecraft-stack/main/install.sh)"  


