AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minecraft Server on AWS EC2'
Resources:
  MinecraftSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH and Minecraft server port'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
  MinecraftVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      # AvailabilityZone: !Ref AWS::AvailabilityZone  # Removed - Optional
      Size: 8  # Adjust size (in GiB) based on your needs
      VolumeType: gp2  # Adjust volume type (e.g., io1 for higher IOPS)

  MinecraftServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t4g.small
      ImageId: ami-079ea43d31a4fb4d8
      KeyName: Minecraft Server
      SecurityGroups:
        - Ref: MinecraftSecurityGroup
      BlockDevices:  # New property for attaching EBS volume
        - DeviceName: /dev/sda1  # Adjust device name if needed
          Ebs:
            VolumeId: !Ref MinecraftVolume  # Reference the created EBS volume
            DeleteOnTermination: False  # Set to False to persist the volume

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          /bin/bash -c "$(curl -sSL https://raw.githubusercontent.com/jstockdi/minecraft-stack/main/install.sh)"  


